### ISSUE TITLE
compilation of locales doesn't work in debian jessie

### ISSUE THREAD

**Issue by fonk** [kellerben/dudle#31]
The mentioned package libgettext-ruby-util is no longer available and "make" fails:
```
root@6d25237bb6fa:/var/www/html/dudle# make
rm -f locale/dudle.pot
/usr/bin/rxgettext *.cgi *.rb -o locale/dudle.pot
Error parsing poll.rb
/usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:292:in `lstrip': invalid byte sequence in US-ASCII (ArgumentError)
    from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:292:in `block in parse_source'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:57:in `parse'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:242:in `parse_source'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:217:in `parse'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:134:in `parse'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:365:in `block in parse_path'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:360:in `each'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:360:in `parse_path'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:168:in `block in parse'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:166:in `each'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:166:in `parse'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:217:in `generate_pot'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:151:in `run'
    from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:34:in `run'
    from /usr/bin/rxgettext:24:in `<main>'
Makefile:27: recipe for target 'locale/dudle.pot' failed
make: *** [locale/dudle.pot] Error 1 
```

**Comment by arminfelder** [comment]
just install gettext and ruby-gettext

**Comment by fonk** [comment]
Still not working:
```
root@1942e66e35af:/var/www/html/dudle# dpkg -l | grep gettext
ii  gettext                       0.19.3-2                  amd64        GNU Internationalization utilities
ii  gettext-base                  0.19.3-2                  amd64        GNU Internationalization utilities for the base system
ii  liblocale-gettext-perl        1.05-8+b1                 amd64        module using libc functions for internationalization in Perl
ii  potool                        0.16-2                    amd64        program to aid manipulation of gettext po files
ii  ruby-gettext                  3.1.2-1                   all          gettext for Ruby
root@1942e66e35af:/var/www/html/dudle# make
rm -f locale/dudle.pot
/usr/bin/rxgettext *.cgi *.rb -o locale/dudle.pot
Error parsing poll.rb
/usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:292:in `lstrip': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:292:in `block in parse_source'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:57:in `parse'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:242:in `parse_source'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:217:in `parse'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/parser/ruby.rb:134:in `parse'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:365:in `block in parse_path'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:360:in `each'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:360:in `parse_path'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:168:in `block in parse'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:166:in `each'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:166:in `parse'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:217:in `generate_pot'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:151:in `run'
	from /usr/lib/ruby/vendor_ruby/gettext/tools/xgettext.rb:34:in `run'
	from /usr/bin/rxgettext:24:in `<main>'
Makefile:27: recipe for target 'locale/dudle.pot' failed
make: *** [locale/dudle.pot] Error 1
root@1942e66e35af:/var/www/html/dudle# 
```

**Comment by kellerben** [comment]
It works on my machine with Debian Jessie. Can you check your installed ruby version?
```
$ rxgettext poll.rb -o /dev/null
$ ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
$ dpkg -l |grep gettext
ii  autopoint                                                   0.19.3-2                             all          The autopoint program from GNU gettext
ii  gettext                                                     0.19.3-2                             amd64        GNU Internationalization utilities
ii  gettext-base                                                0.19.3-2                             amd64        GNU Internationalization utilities for the base system
ii  libgettextpo-dev:amd64                                      0.19.3-2                             amd64        GNU Internationalization library development files
ii  libgettextpo0:amd64                                         0.19.3-2                             amd64        GNU Internationalization library
ii  liblocale-gettext-perl                                      1.05-8+b1                            amd64        module using libc functions for internationalization in Perl
ii  po-debconf                                                  1.0.16+nmu3                          all          tool for managing templates file translations with gettext
ii  potool                                                      0.16-2                               amd64        program to aid manipulation of gettext po files
ii  ruby-gettext                                                3.1.2-1                              all          gettext for Ruby
```

The first line of the error reports an invalid byte sequence. Can you delete [lines 500-516 of poll.rb](https://github.com/kellerben/dudle/blob/master/poll.rb#L500-L516) and try it again?

**Comment by fonk** [comment]
The problem was, that LC_ALL was set to POSIX inside of docker. I fixed it here in my docker container https://github.com/fonk/docker-dudle/commit/2ba166bf17dbf7372e23f098c64a3cb63a46cebb

**Comment by KRtekTM** [comment]
Hi, i'm experiencing the same issue on Debian Stretch.
I have Ruby in version 2.3.3 with libssl-dev 1.1.1

I'm not able to create polls with czech alphabet (which is possible to create on dudle.inf.tu-dresden.de)...
I tried almost all possible solutions offered by google but with no luck :(
