### ISSUE TITLE
installation of ratom gem fails in debian jessie

### ISSUE THREAD

**Issue by fonk** [kellerben/dudle#32]
Don't know if this is dudle's fault, but installation of the ratom gem fails in debian jessie:

```
root@6d25237bb6fa:/var/www/html/dudle# gem install ratom
Fetching: libxml-ruby-2.8.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ratom:
    ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
checking for socket() in -lsocket... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details. You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby2.1
    --with-iconv-dir
    --without-iconv-dir
    --with-iconv-include
    --without-iconv-include=${iconv-dir}/include
    --with-iconv-lib
    --without-iconv-lib=${iconv-dir}/lib
    --with-zlib-dir
    --without-zlib-dir
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
    --with-socketlib
    --without-socketlib
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
    from /usr/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
    from /usr/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
    from /usr/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
    from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
    from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
    from /usr/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
    from extconf.rb:27:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/libxml-ruby-2.8.0 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/libxml-ruby-2.8.0/gem_make.out 
```

**Comment by kellerben** [comment]
you have to install libxml2-dev
