### ISSUE TITLE
Problem with : invalid byte sequence in US-ASCII (ArgumentError): /something/websites/umfrage/xj489mvw/edit_columns.cgi

### ISSUE THREAD

**Issue by himmelbuerger** [kellerben/dudle#87]
I had a problem that if I used non-ascii char it failed with

> Problem with : invalid byte sequence in US-ASCII (ArgumentError): /something/websites/umfrage/xj489mvw/edit_columns.cgi

I tried the usual with locale, setting LANG, LANGUAGE, LC_ALL but it did not help

I then put the following into some files:
```
#encoding: utf-8
Encoding.default_external = Encoding::UTF_8
```
Now it works. I do not know enough to see if this is my own problem or if it would make sense to put the lines in the correct place for everybody.

**Comment by D1Ck3n** [comment]
Hey @himmelbuerger ,

i have the same Problem!

`[Thu Jul 19 14:03:26.649940 2018] [cgi:error] [pid 14273] [client 10.114.205.215:8548] AH01215: /var/www/dudle/dudle-master/vcs_git.rb:55:in `split': invalid byte sequence in US-ASCII (ArgumentError), referer: http:// servername.top.level.domain.tld:8081/poll1/
[Thu Jul 19 14:03:26.649989 2018] [cgi:error] [pid 14273] [client 10.114.205.215:8548] AH01215: \tfrom /var/www/dudle/dudle-master/vcs_git.rb:55:in `history', referer: http://servername.top.level.domain.tld:8081/poll1/
[Thu Jul 19 14:03:26.650035 2018] [cgi:error] [pid 14273] [client 10.114.205.215:8548] AH01215: \tfrom /var/www/dudle/dudle-master/poll1/edit_columns.cgi:47:in `<main>', referer: http:// servername.top.level.domain.tld:8081/poll1/
[Thu Jul 19 14:03:26.652491 2018] [cgi:error] [pid 14273] [client 10.114.205.215:8548] End of script output before headers: edit_columns.cgi, referer: http:// servername.top.level.domain.tld:8081/poll1/
`

in which files did you put your code in? Maybe this will help me too.

Greetings
